# action.yml
name: 'update qbee device config'
description: 'upload and commit config to a group or tag in qbee.io'
inputs:
  file_path:
    description: 'filename without path'
    required: true
  node_id:
    description: 'id of group to apply config to'
    required: true
  form_type:
    description: 'form type to upload'
    required: true
  commit_message:
    description: 'commit message for the config upload'
    required: false
  tag_name:
    description: 'indicate whether or not the target is a tag'
    required: false
    default: '0'
  template_params:
    description: 'template parameters you want to expand the config with (gotemplate)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
