name: 'Upload Qbee Config'
description: 'Upload config to a device, group or tag. Adding an optional commit message will also commit configuration."'
branding:
  icon: send
  color: white
inputs:
  file_path:
    description: 'filename without path'
    required: true
  node_id:
    description: 'id of group to apply config to'
    required: false
  form_type:
    description: 'form type to upload'
    required: true
  commit_message:
    description: 'commit message for the config upload'
    required: false
  tag_name:
    description: 'indicate whether or not the target is a tag'
    required: false
  template_params:
    description: 'template parameters you want to expand the config with (gotemplate)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
