name: build

on:
  push:
    branches:
      - 'DEV-**'
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile

      - name: Do qbee login
        uses: qbee-io/authenticate-action@DEV-2145/convert-to-qbee-cli
        with:
          login: ${{ secrets.QBEE_USER }}
          password: ${{ secrets.QBEE_PASSWORD }}
      
      - name: test config apply
        id: qbee-config-apply
        uses: ./
        with:
          file_path: docker-containers.json
          node_id: ${{ secrets.QBEE_NODE_ID }}
          form_type: docker_containers
          commit_message: ${{ github.event.head_commit.message}}

      - name: test config apply
        id: qbee-config-apply-tag
        uses: ./
        with:
          file_path: docker-containers-template.json
          node_id: ${{ secrets.QBEE_TAG_NAME}}
          form_type: docker_containers
          commit_message: ${{ github.event.head_commit.message}}
          is_tag: 1
          template_params: docker_image=alpine:latest,user=my-user,password=my-password